In [1]:
#NumPy

In [2]:
#Creating Arrays
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print('Created Array:',arr,'\n')



#Indexing Arrays
print('Array variable at index',1,'->',arr[1],'\n')

#Slicing Arrays

print('Sliced Array:',arr[0:3],'\n')

#Shape and Reshape Arrays
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print('Shape of ',arr,'->',arr.shape,'\n')

narr = arr.reshape(4,2)
print('Reshaped ',arr,'->\n',narr,'\n')

#Join Arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print('Joining',arr1,'with', arr2, '->', arr,'\n')

#Split Array
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print('Split',arr, 'into ',newarr,'\n')

#Sort Array
arr = np.array([3, 2, 0, 1])
print('Sorted Array', arr, '-> ',np.sort(arr),'\n')

#Filter Array
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print('Filtered Array',newarr, 'from',arr,'\n')

#Search Array
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print('Position of 4 in array', arr, '->',x,'\n')





Created Array: [1 2 3 4 5] 

Array variable at index 1 -> 2 

Sliced Array: [1 2 3] 

Shape of  [[1 2 3 4]
 [5 6 7 8]] -> (2, 4) 

Reshaped  [[1 2 3 4]
 [5 6 7 8]] ->
 [[1 2]
 [3 4]
 [5 6]
 [7 8]] 

Joining [[1 2]
 [3 4]] with [[5 6]
 [7 8]] -> [[1 2 5 6]
 [3 4 7 8]] 

Split [1 2 3 4 5 6] into  [array([1, 2]), array([3, 4]), array([5, 6])] 

Sorted Array [3 2 0 1] ->  [0 1 2 3] 

Filtered Array [41 43] from [41 42 43 44] 

Position of 4 in array [1 2 3 4 5 4 4] -> (array([3, 5, 6]),) 



In [3]:
#Pandas

In [4]:
import pandas as pd
#Pandas Series
a = {'n':1,'c':2 ,'t':7}
myvar = pd.Series(a)
print('Series',myvar,'\n')

#Pandas Dataframes
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}


df = pd.DataFrame(data)

print('Dataframe created:','\n',df,'\n')

#CSV
df = pd.read_csv('/Users/chinmayeed/Documents/TataIQ_Intern/np&pandas/student.csv')
print('CSV Data:\n',df.to_string(),'\n') 

#JSON
df = pd.read_json('/Users/chinmayeed/Documents/TataIQ_Intern/np&pandas/student.json')
print('JSON Data:\n',df.to_string()) 

#Empty Cells
df = pd.read_csv('/Users/chinmayeed/Documents/TataIQ_Intern/np&pandas/studentempty.csv')
print('Data with empty cells:\n',df.to_string(),'\n')
clean_df = df.dropna()
print('Cleaned Data:\n',clean_df.to_string(),'\n')


Series n    1
c    2
t    7
dtype: int64 

Dataframe created: 
    calories  duration
0       420        50
1       380        40
2       390        45 

CSV Data:
     id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Ja

In [5]:
#Write a program for performing various operations on matrices (addition, subtraction and multiplication)

In [6]:
mat1 = [[1, 2], [3, 4]]
mat2 = [[1, 2], [3, 4]]
mat3 = [[0, 0], [0, 0]]

for i in range(0, 2):
 for j in range(0, 2):
  mat3[i][j] = mat1[i][j] + mat2[i][j]

print('Addition of two matrices')
for i in range(0, 2):
 for j in range(0, 2):
  print(mat3[i][j], end = ' ')
 print()

mat1 = [[14, 12], [13, 24]]
mat2 = [[12, 2], [8, 6]]
mat3 = [[0, 0], [0, 0]]

for i in range(0, 2):
 for j in range(0, 2):
  mat3[i][j] = mat1[i][j] - mat2[i][j]

print('\nSubtraction of two matrices')
for i in range(0, 2):
 for j in range(0, 2):
  print(mat3[i][j], end = ' ')
 print()
    
mat1 = [[4, 2], [3, 4]]
mat2 = [[1, 2], [8, 6]]
mat3 = [[0, 0], [0, 0]]

for i in range(0, 2):
 for j in range(0, 2):
  mat3[i][j] = mat1[i][j] - mat2[i][j]

print('\nMultiplication of two matrices')
for i in range(len(mat1)):
 for j in range(len(mat2[0])):
  for k in range(len(mat2)):
   mat3[i][j] =mat3[i][j] + ( mat1[i][k] * mat2[k][j])

for r in mat3:
 print(r)

Addition of two matrices
2 4 
6 8 

Subtraction of two matrices
2 10 
5 18 

Multiplication of two matrices
[23, 20]
[30, 28]


In [7]:
#Write a program for performing the matrix rotation using for loop.

In [8]:
def rotate90Clockwise(A):
    N = len(A[0])
    for i in range(N // 2):
        for j in range(i, N - i - 1):
            temp = A[i][j]
            A[i][j] = A[N - 1 - j][i]
            A[N - 1 - j][i] = A[N - 1 - i][N - 1 - j]
            A[N - 1 - i][N - 1 - j] = A[j][N - 1 - i]
            A[j][N - 1 - i] = temp
 
# Function to print the matrix
def printMatrix(A):
    N = len(A[0])
    for i in range(N):
        print(A[i])
 
# Driver code
A = [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12],
     [13, 14, 15, 16]]
print('Original Matrix:\n')
printMatrix(A)
print('\n')
rotate90Clockwise(A)
print('Rotated Matrix:\n')
printMatrix(A)

Original Matrix:

[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10, 11, 12]
[13, 14, 15, 16]


Rotated Matrix:

[13, 9, 5, 1]
[14, 10, 6, 2]
[15, 11, 7, 3]
[16, 12, 8, 4]
